import { CssBaseline } from '@mui/material';
import Head from 'next/head';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { setUser } from '../_features/users/usersSlice';
export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setUser());
  }, [dispatch]);
  return (
    <div>

      <Head>
        <title>Appointment Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />
      <h2>Home Page</h2>
    </div>
  )
}
