import {
  Container, CssBaseline, Grid, Typography, Card, CardHeader,
  Avatar, IconButton, CardMedia, CardContent, CardActionArea, TextField, InputAdornment
} from '@mui/material';
import Head from 'next/head';

import { HomePage } from "../layouts";

import SearchIcon from '@mui/icons-material/Search';
import { dehydrate, QueryClient, useQuery } from 'react-query';
import { shopService } from '../_services';
import React, { useState } from 'react';
import { stringAvatar } from '../_helpers';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
import { getShops, selectActiveShops } from '../_features/shops/shopsSlice';
import { unwrapResult } from '@reduxjs/toolkit';


export default function Home() {
  const router = useRouter();
  const [search, setSearch] = useState("");
  const [msg, setMsg] = useState("");
  const dispatch = useDispatch();


  const { data: shops, error, refetch: refetchShops } = useQuery('getShops', async () => {
    try {
      const result = await dispatch(getShops(search));
      const data = unwrapResult(result);
      // const data = await shopService.getShops(search);
      return data;
    } catch (ex) {
      setMsg("shop not found");
    }
  }, { refetchOnWindowFocus: false });

  const activeShops = useSelector(selectActiveShops);


  const handleSearch = (e) => {
    setMsg("");
    setSearch(e.target.value);
    setTimeout(() => {
      refetchShops();
    }, 500);
  };


  return (
    <HomePage>
      <Head>
        <title>Appointment Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CssBaseline />

      <Container >
        <Grid sx={{ display: 'flex', justifyContent: 'space-between' }}>
          <Typography variant="h5" sx={{ my: 3 }}>Listed Shops</Typography>
          <TextField
            label="Search"
            id="filled-start-adornment"
            sx={{ m: 1, width: '25ch' }}
            value={search}
            name="search"
            onChange={handleSearch}
            InputProps={{
              endAdornment: <InputAdornment position="start"> <SearchIcon /> </InputAdornment>,
            }}
            variant="standard"
          />

        </Grid>
        {/* {!shops && msg.length == 0 && <Typography variant="body2" sx={{ my: 3 }}>No Shops are registed</Typography>} */}
        {msg.length > 0 && <Typography variant="body2" sx={{ my: 3 }}>search shop not found</Typography>}
        <Grid container maxWidth="xl" spacing={{ xs: 2, md: 3 }} columns={{ xs: 4, sm: 8, md: 12 }} sx={{ my: 'auto' }}>



          {activeShops?.map((shop, index) => {
            return <Grid item xs={2} sm={4} md={4} key={index} sx={{ height: 'full', }}>
              <CardActionArea sx={{ height: '100%' }}>
                <Card sx={{ height: '100%' }} onClick={() => router.push(`shop/${shop._id}`)}>
                  <CardHeader
                    avatar={
                      <Avatar {...stringAvatar(`${shop.name}`)} />
                    }
                    sx={{ fontSize: 'h6.fontSize' }}
                    title={shop.name}
                    subheader={`${shop.address?.street}, ${shop.address?.city} `}
                  />
                  <CardMedia
                    component="img"
                    height="194"
                    image="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUUFBcVFRUXGBcZHCIdHBoaGSAaIBgZHRoaGhodHh0aISwjHSApIBkZJDYkKS0vMzMzGSI4PjgyPSwyMy8BCwsLDw4PHhISHjIpIykyMjIyMjIyMjIyMjQyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMv/AABEIALcBEwMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAEBQMGAAECBwj/xABGEAACAQIEAwQHBQYEBQMFAAABAhEAAwQSITEFQVEGEyJhMnGBkaGx8CNCwdHhBxRSYnKCJDOy8RVDkqLSFpPCNDVjc4P/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAAuEQACAgEDAwMDAgcBAAAAAAAAAQIRIQMSMSJBUQQTYTJxgaHRI2KRscHh8AX/2gAMAwEAAhEDEQA/AJ7HFkOhJU+f50xw2K1lW9oP5VTyp2iu7LMp0JHqq6EWu5fLOzFiSTudfKmPDeKNaMjn7a85XjV1GaSGEncQd+opphe0Fs/5gdT/ANQ/7dfhUDLbisWHYnmeQ/KowZ5e+l+Gxltx4GVvUR8uVFI/nQAQlonb4V21sruPr211gsX3bBo2qfHY0XGLDQ9BSAGU12Kjidx9eyp7eGYiRJA+t6AOYru25B6/OuI610poAZHHsy5eVD71BNdhqYEuUVmSNq5V67BoA0KZ4W7bCMGGvKg3wpyZzt1oJmProA3eInSoHXmN/red6kzTWqQyJWJ0Ig/W3UV0E866ZJG1chiN/f8An0oAPfhxFvvOXrpVew6tqRqNiNI/CmLYtiuWdOlCsKGgB0bkdx8R1rbV1ctT6xsa4RvKDzFA6NE1yT5Vq6GPokD2TXSgxrqfVFKwoHSQxX2j27/H50PjLrRCQTpMjSJI6+Wm9FXhEN0OvqOh/A+yuMTh2aChUHnKzI6fjVx5Oj0s4wmm/wBeBfewDXAGZ2zAa5DlDSQBrBaIJJM9fVQlrglu2pAUO8k5ngySNVE7kyVA31J1J1tuA4TNtmBAA1Ou5gDQeyhktoASfS26EDcEE0mu5M9R6k6vGStvhms21QjxMpa4SZ5eJhpLesaSTHOqnhb/AHq3DIlnkLsQFGW2rAnYbwObHXer9xDBLFxQCXIIE6ySNIM6mfhXn/BeC4hr7O1l1kMczKUGZtdMwBjUgQKx1E3F0ZaqdUhVca/JlCP7DWVZ72HysQbeo38YrK5Pd/lOS34Hgw9YuGpituultV6ppZVb+A1PrNDPgjVubC1G2CHSpopSKe1gjWibPEbybXCR0bxfHf41YH4d5UHd4Z5UqKszDdo4/wAy37VM/BvzprhuO2n++B5Np86r93hpoHEYNgNqKAv1vH2yYDrPSQfhvTXC8SZEZANG32ryzB4UsNBtR9nE37fou0dD4h8dvZSoaVl+7yaLw2FLhiDGUSeU/nVHw3aRxpcQHzX8mP405wfHrTaC5lJ5N4fnp7qApjmK6DUOl8HmD6qNOIQ2wAPFzPUeqgDia2Ca1Ztl2CrueVRPbAOoEikxpBTYpsuUnT4VCa4DVnqose033c+vrW2BXf31PhL4VhKiPVRnFMSjRkEaUCzYOuIUWymWST6VAtXLeWlaD9aVlbTNR6vl+ddLrUxRO7zZvFMZfLrNDExtTCrDcXYRUUhpJGo6UtuDmNx8R0rtnnr8qmt4ZmRnHorvr12oGo1yDB5EitFq5Yxry5/nWFqVle2abURXFljEHcaH2fpFdE1HMN6/mP0+VMpaLCluNECaDvOqsoYgFjAHU76U14diUQyyhvI0u4jbFzN92ZEjQqDvlP3fXVO6wOHp5ydJE+JxlsahCfcPzqv8T4n3iMhtwp6OwPvXKa7DoGRgr5FVrY+6uUgPmMyYBtBQYE5xvvVcxXGO8uG3atqBuWYsWKwrZlhgBoeYNYydGc4uD2yFF3h6gmBpylj+dZWYziBztlXTlpHKsrk2T+Tm2HpYWpESgbOIu5wr2hlbUFSSQvVukfjTvAYNrhhRp1MwI8wK9NO1Ymq7got10LVNeJYAW4yq0ZRLbjPO3lpr7qCC0J2AObIrhsMKNC1vLTAWPgx0oLF4AZTpyNWHu6GxNvwn1GgLEfZ3BAl5HIfM01u8KU8q32eSC/qHzNO8lA7Kpf4Ep5UtxPASNqvhtionsClSKUmeeph7tr0GZfUdPcdKMs8duro4DD/pP5fCrTfwYPKlWI4UDyqHHwbQknyZg+0dqdSyHz2940pvYvq+ocEHmNaRLwMdKhucGdTKEg9QYPwpUzSMYtl2sJYC+JnZuui/AVziLaLEGZE7/D11TRjcTbH8Y81194iuT2uCD7RHB/lhh8YrVaTcbPRh/wCc5Q3J4LYxA61E4qrt23Qme6usBpsBoBtqeQobFdthl7xLICknKDdEwNdgKxl09znno6cHUmW9W11reJcMxIAAPIaxVBv9tcSCVFpFbbxBjrMdRQY7Z40xJtqWOmVBMTBiSZ5eWtZ7znm4LhnoTXCP1reGxVskZ38J6RO06TVR4xjrjYdWe9ce6wCgSFzWznzKbeUBIhDrr4jyo7svwkv+6m4CAt+6mUQRP7rKhhuv3yBrufKnCdnO9a+EMcZxaympuqNo8QO5gaDeTSS925tqcuRzrHhiN4nUz5xFT4vhoCKUE/Y2gwysToxEiFPnPOVqn4zCh2N1QqfaAZZzRmGYHq0SFpt0xe7K6LUO19slAtu4xuNlELzETOo01+dTW+PqTbVUb7RrgGwym3nzczochj10p4dwgzaJugRcJheZAzEbHUgH41LhlD3rKga23uhtZ3t3TOpnXMNPI8hRGdnQpyXIVf7TKlu1cKH7UMYmcuVo1051LgePLeGilWHiAPSSAdOsVXcdh1a3g4aGW0xb/wB45QPPQ0uxD9265ZtMAAxkw5zOJGXYEBfbm6TQ506N4ep2tKSwemWMUDB3FdYq/LEhcoOwEwPfSHAXXKg7+rUeevPWaZXbzXGUZs7kBY6HZV19nlrWkZpHow9TpxadEl7hIv2gWBPjgwzKSmgIBXX0oJGkxE1TrnD8iu1slWFzu/C2ndLGxAPjYDXNOsV67hcEbds2gGgbMSpkmSduhPMCqxY7L3LbrAtZFcPu0yImBlPTrzpTabs8X1Gp7mrKXZnl1y0iki5dCPuVbNInUTCnkQfbWqfdpL2G/ersW7Z8Wp7sGWgZjJGstJnzrdc2+Pyce+PkunAk7646i4PB4JCzmSTtJ0GYVb7CW7QyIwzkc5MkaeiPM8ulUTsbxm0huPcYIQABKmCpO+ZZ1k7b0/wT2jfa6ztmDEBTqY2BAEkgz7OYrZSTSSCJYBhbjKQzLJXKSsj1wu2sL8egpX/w26Pue4g/jTDDcXt3LhtKHzgSZAET6zPntzpk2m+nrrZUsIqitNhXG6N/0mo4jerUrTtW6dhRVgKgxGx9RqPBce7zGHDth1UZnGfPmnIGIOXKBrl+NWx+HWmGtseyR8jRYUU/ge7+ofjTkGmNngdlJyBln+Yn5zXR4UvJmHuNFhQtArTCicdZSyAz3EVSYBc5RPIeZrtuHORoV95/KkULmWo+7o98BcH3Z9RH51E2HddWUgeqgaIktCtvZFSrpXRpWaJA6YNCfGBl167xp6Ou8fGqj2t4Iq2FuCSxJkSukEhSB6RBPP3xV6SypUEuFJJAB5wfXSXj3BmuoVBQjQyD0M86paqSaZ6fptfbhvHj+v7/AKHn+CsQty4uUAQxtgmSwEmDuBsPbG8mh8ChUO06BQxMSNWyqM8EosPEAEmPWad8PtqLGIVyczEujD0hKMh1PIwBp50ps8XNtNEGcjJLKSQV9UAwJJJHLlXny1Mpdha1ymm+EccP4aGW67M7hFLMR4gyiGGXNqdG1zKNFnnrPhOAzfQJ4shGUDVSNSZMj7o3BjWnPALlpzcyMuU6sWABuyV8G5EbAxtE07w+BNm3mZkGuUNIAzkFQFBkiJn+7Sa8jV9TNTaV/wCjnWgpLPkq2LwwcI6K7FGm5mQySScrhgJIAVfeN40suL4r+62FuW9QtyVJXwkm2F1YaffeDvoOlQ8HwFp7r23J7srlk6aP4xMdYPTYbmaVcUtsLBtspjvSi5zPhUhtARH3QANdiPOvS0tROKo456fL4GBdGw0kQGwykkAbG5DDQBpzGPj0qt4HBNdvW1FtQoa07TMMWyJoDMrAOmsc+lF4J7vdXLSswTNJ1zFbYghgI2kHT89LBwbgri6l246qTq5mAxBzg9PRjQaSK1lrruEdJyfHBWsWzWraJ3bK9tyywToCjJn3kiM/rPvpXaxDpeti2veKrGWgDMWd3IlgJAdzv132NW/t7h7eZHCnOLRSdCvhZjETOYkbgfeqn/uVy0FVho4BCoZPR/OAQJ06DrTjqdvsaSVXj8hCXM9q2ptNmtg2ySjQIOcHMp9Is5AXUaTUGGt57lpLizbJCkFf43kEEzOuoO+jeYojEvkbJbZhmth2BMycpmFPMFQTrzJqfswmfEWrQUFi/jadVWG2OkHUHad9pq07afkmapXz2LYeHImnn5iZ5xyFANadbgZJ8LBhvEgg6+WlG3OE3NZdj6ydvfTHhWDy2wDqZPzrqcEZ6eo7G2KxNxfvD/p/3pVxW7da23d3e7aJDECNNwZGg86acYYrZuMJnLp6+UVXFw+JvWodFBL6hxl8AHIb7zrWc44wLLVHnF7HXCxPevr/ADkfBdB7Kym+OwdtLjKbdxiNyCImBIHqOnsrK87P/M4q+SL/AIjcRDbzArmluhby8ukjSrJw+3mvoC/ekorZWYpnLKPRfWQoPODIqtYfBvcVnVSQpAJiRrsT5THLnV57Pdn7lsd47KxZNC0llzL4YkeCCfnXfCDfJ0pZDrrW7FxH7tRlC5nGrbnWYk76zvTq9xFDbNxmHdgZieWUazFV3tPfyTmUtCrIB1PXU70ZgbguYKQDDW9oBMEbRsT5VptrJpdsmscTw9xkVTJurKeBtVOkzGm4361ZLQgAdABVA4In2lgKrC2qhQWBVtLi+EhtQCAKv4NEJNrI5Kik4awBjQ2xDv7mVvzq7XHhC3RSfVAmvLeE3ieJf/Url7y4O6yElz9p95iYI1OkTBr06/8A5bf0H/Satkoq3/rFc+Ud6dYH2awfjPwp1w/ib3HCyu0mVMxpzBjnVIXCgXAY1mrVwI/bRl/5ZhhMbpM6xPTTkayjNvk65QjtboI7XWw9mD1B9xFOC5CEgSQCQCYk9Jgx64qvdtMYLdu2pIGdsuY7LtqaacTtG5hbqLEtbdRO0lSBPlWj4ORci3hfa+3fLDu2Qqpb0laQJmCu+mvtoztBiX/dWe2WttKRtIHeLI5jUSPbVL4Hh2t4u6rCMttoyjwlWiBMaRk0BPMjlVy7UOVwrQVBm2BnYKNbiDc/U1lpTlJuzaUEop/cavdVVzNt6ifgAajsvZuQVyNOogbj3eVD8ReLXt/Ot8OaWuEk7+fMt1/Cqb6qJS6bEPH7YK2x0e5/qFRcNwIys7aDKQPaIJo7iFoMQszld59uVo9xFThfDA6fhWbXU2dKl0pHkfGHNsNcR8sqECAZTmDHxCORBYkbneaTYu6oByMxYkoAfESfunbQHMZ5+E9atb8NRlK3BOszsdDIg8tzVSxvDWF2E2B5nyrni420+39jomp0mgMO+bIxC93ruQdSPCImD9TViwfEboKu11jkJIzEkCRDaHqsj1Uqu4GNbkFydSCdek0z4bYR84fNAtu3hOUmBtMGN+lTPbJcBBOLply7NYW5cPesbgUZm1WM1xmUTrtoZmOZip+1VsNaePu3yNT/APjAETp6TTBI5mZ0o/sbiO+wzE2+7i4y5c+YeE25Mx1n40J2ptaRAOe8wgkn0lU5hqIIy+e556jSMNsEqOWeW672JOzyG3cByNFzD5s52YiDEDbaNZ5dRVj48rGFtki5nXLlOwgggZjAmY1pXd4STZtvbcoVsI0TmBVCxIzCDrn9wp7xG6yFmFsvlNs6ESTPogbydB7ahxy2XppRjTFfFcL3ty0G1Q3WDL/Evebe7Q+U0p4ngjKXJyhO9CgRmzd9d0BIgBhp7acBbjXbNwjL9qwKGCVbM5PiX0tOXtqfuFd7QYAjvLu4nUd8QfYRVL9v8A4uVtivAcCuXsOz3oS40C2RBa2qtpJGhJhZiJAANQ4BP3DFC5cQOplUZdHZtCzONF0B9Llr1q42DFtfVVf7Q3bK3LBxCK9sG4SrAGT3ZAgEiTrtXSo9KZWpBPTfkYNxC3IzYqxHMBlE++4flRYvyiG2ynMfCZBBkjYjeqdx/D4R8Bdu27Nu2He2VZbKowXPaBK6bHU6GCG5zUvAe8AwSW0uNbcWnzk+FchykbQpyhCRz5QatzOBLay6cbxwtd2CoYEgR5k6fGDXV3EfbImmUj5KW9vPlSjtZiUW4puz3dqCxVgCzMG7u2itIL+EtuIGs7A1e12yuHF95etstnU24KyCIVWYkw0jPoOcEDQzm3kbaQsxnCGa45Ktqx+6Np00J00jTltWU+vcZVmJt3cMqH0RcxIVo6svInePOsrD2YmPtwLTwLDBEUZmJQFZK5ZzEGdzr4etN1NQ37Xcr9dDUqEEA9RNdqdGu1sq/a51DnMwUZd2IA3HM6UfwQ/4NIIPg3BBB0GoI0NUj9pnFQcR3SXkTIoDqZkk+IKfCdMpU6dasXYniVm7ghbt3AzWkCuAG8OhC+kokHKdfKhsSVDbC/5lv+tf9QqzzrVM/fbdu5azsFz3FRd/ExfQaeo1cSdamBcmeUYG0BxNW599dn2i4Pxr1a4fs2/pPyryq2bn/E1y23KC6+Z40Hpj516o/oH+k/KrI7lG0zqJ1J0HXrTrgBH7y0Nr3ZkQeqazEf71XruLt22BuXESNfEwB9x1pj2U4pavYxu6e2/2baqTIGa3uCfw5VjFcHTKXS0F/tAWbVvyb8UqxOfsm/pNVvt+y91bDvkVmIzZS0eidl15b044niFTB3Xb0Vtuzf0hSTtrtWr4OePIlVURrlwkyywdeQW7EDYbn6FHduyP3J/6rXv723FU/AcftXGILplIURoNMr5gZMj0lq29vCv7k+YErntSFgmO9t7ZgR7fdrWemmrs31pKVUF9ocT3eGLxMEaTGpJG5rjszxFLxulREZekkGdTG0mdKA7dsowJLsFAdPESVAIaRtv6jpSn9mWP7y5i0mQi2oMRqTcnl5VMlLemuAi4+275LE2Ka5qwAKu6aTqFaAdecUQm3spfZPp//suf6qMzeE+qjuy/BSMW4mq3iLil9GUkbwQSPXRnaPElbbQYPWqCbdwKWKPk/iKnLr5xFYLRvNnRL1G3posmOxSFgMwkee2lS8PxIVbzTIFm5sA2+UbHQ71Uc++g2PIaafA0ZwGy9y8ioYJ5zEDrprAq1pKK5Mvec5cHrv7Oce74FrjFZFxhIVRpNrfKACdTqdaN4qjXXVM2+IurpGy2WYDbqNecV12cwYtYdkR84zzObNr9mDqSeak+U0U6kXEkkf4i6R5g2X+HP2VpGmsIybkpc8AVhv8ACLO/7nPwWmpRXdgSQQ9snbUghlAHnEH10kv3wuEZzJAwRbeSQAOfXSjriPcu3URoK3cO3P0UZbrjTqqke2hQyVvSWAh8KJQ54i6z7bk5/Dv50DZK57OUyO8v+WoF6R7DI9lEYm07NakqAt520nVctwLuPS1E8ulLMOwW5hlH3r2KA92IY/jScKZe/GR7aP2a/wBI/Gqb25YHuENy3bDl0L3BmUAptptOgnlNWbhWK73C2rsABlB3kCCwOpjpVK7W4vCYh7Vu5dYopbxWxIzEKFAaIPPUaedaLCRUn/DZmIuFeH906lWLJKklvRyCRmJgHLmA2AIqz9mT/hsIP5V/CqZjbgNsILj3DPpOPFA2kwAdANauHZs/ZYMfyr+FD4OWGW/sNu1Fu2uFu5rndIcudyC0LnTMxEyx289q814z2WuYe33igOoLM+fwlNVVAQrnxNPKdCBXpfargrY2w9kXBbDDUlc3otbYaSNfDvSsYdHzNMvdKh2klXIVobLMEZxMdDFRNrH3oxcW+DytbSn0lUHoTb06ekQdo3rKJxnCCjstzGW1cGGBJ367c9/bWUtpNI9r4+hdWe0QwDAnKZ0mCNP6gYoqwjd2kDXKN+sfCvOLva7GyQAggxopPzJrhOOY5/vwPUo+NW5o6IxlQu7edkcbexl+/bsl7bZSGFxNctpVbwlg26nlyqD9nPEFsWMdcYE+BcoA9IoLhYEzp6adedJ+Ocfxq32VsTc0C6K7ZdUUxHPz85ojg/Grji6rpnV1I5AIe7fXaWLHINdoq08WRJZHmF7SrisRhli2sX7Zy3FJ17wCVYSM0ExIG+9exE6181dnQf3vDb6Xrc+UXU3r6GxPFrFsnvL1pf6rij8aaJZ5lZzpxIQ75WvvIzGD4n0ivW7mtsj+U/KvHsTxG0uN703LXdC4XkOCWBJOirJ586fY79q+GQZbdq5cO0khR8ppgeVpxVyqi5F0AaC4M0acm9JfYauf7HDOPcgQO4uRvHp2jEmqT31jlac9M13/AMUFXv8AZPj0bGBFtBPsrmzFtJQ/ek7+ceVIovX7QBNhP6j81o3tBcI4diSDBGHuEHz7tqpn7VePXLNy1ZCobbW8+oM5s5B1B28IqmYvt3jrltrTXR3bAqyhFAZSIIOmoIpkJFeOHuMMwE5gTp1102idNvMV7723xSNgnRHRrh7uFzqDo6E7nSACfZXhf/FbiKBbItkzJRQpI0gSBI57UA7ljLEsepM/OkUe7dpe12CWwALq3Wzr4bcNBEtJ120361UOE9vbeF7027RdrgAkkIBlzEEgA5t/KqJhsIXs3rg/5QRj6ncW/wD5UCHpNZsvc1Hb2L9c7dXEDXFU5mYnKz+AFpJIAWd40nnSp+2ONb7U3iIPoqAF9WXn7arTPKj1n8KNweEuXVNu2stOY6gaAdTTSWbEnLsTt2gvFW8cHTUASNeRjSouGtnuDvDmBInOdxrMk1y3BMSBraMExOZYnXc5tOfupvwjgcH7YKV6BtTy3Aj/AGpDW5vIoPDShRzAAIMA5+YIkrISdNzTHsg1u1ig7XBlhhoryJ8iscuR50/v8Awk6C6YgSLqjQeTWiRFQ2+zNuQ1q5Gno3F2/uSfiorOd5RrFK00encLxtu5bLo0oGgnKRBlTsRPP413dVGuKc2q3HgdW7kgg+wk+ykvZjAMmEuWyyZi5Kw66j7Pz8jv0pw+Bud4rASvfu8gg+BrBQHf+KBG9OMcIicupi67wdv3drRcH/CdyTtJIjNzgU2w1jJcuP8Axsv/AGplrm413uyzWnzd0GKqJ8QGqD+aq72s4x3d393IdCVzo8eEmWn+rdfaDWlE2EcV4wLOVZTOS5AYxIVoMHbmPfVW/wDUbqq/ZsjI105lfPrcctoU5AEjek+KuX2YF3S6qzlnRlzelBIMTpPqoZmH3kup5jUe8ZvwpNWNz8DfH8fa8uRrjMN8rsTr6s2vPlSHiGHZ8gVQdSdCDIkdNfhXahG2xMeTWg/zYfKuuF4VkbO8MjA5GB0aGgwu6wZ3AqVFRyinqylHazg22A/ywPaf/GvROzNyUwgGmw9xj8KrLWrZEywPQAR783q5U87NYsjEYdd1UwOo8JFF2TFVZ6NftFbZJB9FthJ93Wq2cG3d5gBAuZumgfz12mnuP4xatQLmbWYhZ2350ru9psFJUuAd4KEDXUa5axnsfS3lO+RJSq6wC2MDhyJcpmJJPtJI+EVuqRj+3UXGCTlnTu7asv8AazasPMgeobVqnv8Agw3IEHDYOtxifJffqTTbDJC5crQBGpAmhS1zclF90/ia6uIrRNxvRAMDc8zqazk2+T0IpIqfaTCqb9wJbuM4CzElV8I56kmnPZTA5LE3AczuWyldQICidJ1gn2imuGwhA8MZeWfU/wDaBTbDYUkaufUAF+NbxfSjln9T+55p2jt9zfZLeZUYBwJI9Kc3skGlAYVbP2g2Uz23RsxAKPzhhDKCY6M1U81ongk7Z5FcTWhWUAdA1fP2Pf8A3H/+Nz5pVCBr0v8AY9hmW5fv5CQFVEbKIlmOYKzf0gGOooBhv7Z8L4cNe5AvbP8AcA6/6X99eV5q937cgPYS265s1wSFgkDKxnxDyA251Xr3Zbhty2CLF2253KXCuvqYuo9i02JHlDHQfXM1oVeMb2HRCCr3ShD/AMEqVQuASYmcp2HI0Xb7L4Sys3FcncF2nltlXLO4+7SGEfsosW8mJNzKVud3bysAQwGdnEHcarT/AIhwHh7g5cEk9RNof9pB+FGcKCi0iLbKoskCMgBgDQaEbDl867vXVbMYZcpI1kEwYkRIIPI6VDnmjVadqykr2WsAkCyWJgL43KgjJmOjAmcx0jTTzp9YwQVHsrbS1rnAWACuq6EanWN+vnXQ4gocjM+YAn7uobKIzGRpkGmWicQSwXVjPMwYGusrlI1EaSZ+A7Y41ESpaVGjOMwYEExKwCDHM7jXWiMThWcqc5duXjAJ56AgE0T+529+7Vm6kn9aIFwJ9wgf1SPYCdPYBUubjwawzyA4jCtJPdmTzGv6UMAwMEEH660zv4p29GB8TUNnAk+Ikj21DnKUm2XUUqOrDMBEA+yi75ZQuiajSNDud4G/nXNu4ACE1PM/771MuIuW9A7Anoefqro0pLa0znlC3g4xOMuW8mjDMsjI51Eka+cg+4VV+3N9y+Fdg4OVwCzZswzDzMagj2VaLveXHWZMDc8h7NqrP7Q7RS3YYsPDcK7RGZWb5rW7cc18GbhSTK33xPOukxTDY0tF2tm9WIg3HY1mUg5YOh8I+HTblRHBMPKgkQp2YCTEmZ9vLypOt4FlDejOvq1mrzwqyqW1CjSJHkJ0+dJlRJcBwh75y2mV2iYPgjadW0ME1ZOEdlb9q7bu3AoVDJhweRofs0qm6NPPXUaOp/CieE4q614TccqS/hzGNmI8O0bUgb5obceXNabKuciIAI1OYfGJqo8Z4YbiWciEZlOZgPFb9Bh4hz9JR0Jp9jLyi2c5GadNOfPlv7aRi5ca1q1uIG5AO2uuh3rknTe5rsUrUaTKVisNatMbffW1yx4WsuSNAYJza71lS45E7xpbn69OXwit1nvfg46l4GS4q4xJS0NebAny0JgUclu5lXMwQxrGkn+3yiprlnUsWYDoNOVL8SHzRbT+5tdf7jFapqWFR6fHI6wXC71xUKCUMg3WuqkRM+EksYOmk03w/ZtwfFiT/SiF/i0CouzFxu4UXHDNmbUbb6AaD6NNkIZnzAkZoCkkiAAD4TpMz7q6YJbUcc31MBxvAMG6FL2a75NcymeRC24afaaqWP8A2b2G1tXbludg4DgewhW95q8YnEqMqkqgBmPYY8I1OppFj8ddzHI6leqqV+D6g1eETZ5bc7PMrXVziLdzJ6JljmZZAB/l286Z8H7O4dmm9ccpJE2yAZABggqYGvUU8uYUsxJABYyTpJJMk8yaJwOHGYq2oDHfkoRPcJ+dNVTCwzh/BsBbQsli2TknPdbP4o5C54VO+3QVZf3tnUZc8aESVUACDACEgiq/dS07JbDq0kxba4SGKifRPpR0JI02psmKuKPFbn+n9JqWynFnGJsZtWMf0j9altoiLIA9pA+FL7+PBMQw+vfUFrDWzmyGMxloJEsdyfPSoAn4hjgxjMjAclLk+JGXUZf5uUmphcYgBc4YDTMwgkaeEEZvlSy5wt7kLnyqpzSJzMY+8SY01iOpo3DcOy65ifM/rTbQ0MsALjqjNmQkSUdYK+RjnUmJshv8xEbKZEbgwRInYwSPbWYJCv3naTMsxMabCdgI0GwrWJvqu5k9BvWLjcjVTqIDdVQIFsgzuAD8qjtZdYEE7wsSfPTU1l68TvoOg/GpsNh3YTlCr1/Ic6umJSOHuEabfP8ASurWGLakQOp3PsNFCyqagCep1P6Vw94nfnSkjSLs3ZsL4gmpUEnaYAJOgknbYA+qo8fw+6ASYhd4O3viT6pIqF0nWI9kf7VImDL9Y69KzTNXSIcMIBAEn6+pqe1hWJzQCaaYfCqi6D9a25gVSkZsitWyI8IneAfn51C1oHNmWROzLNF4JcxPqrV57ZUsLikH+DxxpzjQHbSae57qBLpso/Eez9g5soUvrAFq2gJJ2JtoPfVdv8EtLnUK5dWZNXEBlcq0wR4dDGhM/C8jFg+B7iSOQV1OmukiD568jS792Vs5UWnZ7jtl7wIy5nYmQ8TvsCa2yYOrK3gOBKrhyof+QtIMiNjrz6167wzgNgIguFlu5RmTOBlaBIAH51SOFYQG9bV7b227xRlaRIzDUTyNOcZhw2Iuvmb/ADG05HxZaF8ib8FvtcBso2dcwMR6QOntFLsL2YW1dS4l0kCQVYCSCrDQjeJnbrS+yzLjVQE5JMrJg/Zzt66AtXnGLJS44Cm4AC2YaK4BE+o6fnVEJljxPC7mQrlDnkZGnsZvwqscVwF61ZHeAAQqk5FYAgDmZ3g86IxXanEv3gwxtsbLEOXQMIVXZgAjAzog3+9Sh+3d29auq9u0TERDLBJOsNmmImPlWGto7YbroJatRYgvr4j4Z132msoQcbuD+Af2If8AUCffWV5tP5OCx6+b+ML0A1PwqJpVgAjXGInnp64mobl11JFu3A/jf1TzgD41ymHd4Ny6Sp5LqN/YB7jXoKNZZ7O7tEYYZS4Pebz6IIIG3mY+dM8OCBlDMF/hzMfL0Ziq+jra+ztzl311JnzgfAUZY4i3MCPd8q1jW1Uc073MY3iq6beX6ChnxtoZlNzxj/lrqwkaFpIAXUcyfKoxfVj09dZfwqHxZRJ3PX21RBX8ZilV2YIpJOuZi0RoIGgHuom3ix3a3Ap+0LCAojTLOhBgbbV3csJO3wojA4UqfTMawsyFkyYHKdPdT3Yoob8JxSwpuIjlfRm3qkiCQRB209tPcNi+8dosm2ixDk6OTqYU6qBtrvS3A241A16k07SNJNK7NZNdgfF2lbcT7J+FBG1GwiPrbYU4u7Uuu3ADAGZug+tKkybAVwhmcxnzqbPk0JLH30SMO7ek2UdF/E/gKExNnJoHB8tj9eujaNMkbEOwgGPIb/DaoFSOU/XWu7cDfU/XKjLWDZtToPrYU6RaQFbtSdR7BRHcZdZI9RpollUHSh8RdzctPZPx2oZaigBrhnT46/RqW2w3Op69K0TrAG317qltwNTqfl6qzYzoICdZA6UUWUbQSNh0/KgsQ/Ib8/L66ViXisQoI+tTUpGnKGBGkyZ+vcKV4nGkmF2+fq8qlxGKLLERO4mZ+WlCogG+5+tKcSJ4D+HYsqToDp1qHGWrZBKplneNieZINawqnxH68hUGOuaEcyI9Q60nDqsIz6aEr4cK2ZVDkBwAWyg5kZN4O0z7KQLw0gmW8RMnY6nU09BYazp0pZjhmaQPrn9eVaJ9jFjnss9394s284NvOJVlmAJPhn0TpuKPF/7RQR6d34Z5/GlXZi+lm9buXGhRPIn7jAaDzIqDDYp1Af7w111hgZ2PnV2QW/COpxzg765fMhBI26T0/CuOFC2uLd86AkXNMw0YuFM/zRNL+A3jcxVp21ZsxJ217tuXu91R9nsOHxt0bx3hIO3+YBtHU1SyBb3wgOaIBaJMb7zJ86pfa/BkRMHfUaETEAmddumlW67hZxK3SCQtuAZOjeMGQDro3OqP2ye53rLJMsMo10GRNvItPtFc/rL9vHlHPrfSUq5agkEVlZeujMQzCQYOkbafhWVxdRzdXgb31UH7R2uN5aD3mT7hXQu3CABltqPf8ZPyrbPBMkKPidPLU1GboYgKhYjmfxA/GvSnBrk9mLjSZ3hlBk5mfXVm3O3mT8aILACo8KrHVo/tiBtpppRyYMty9/5Uo8GWp9TBAzHapEn+YnoPx5UcmDg66+38KLSyvL9KogBsYctvA+vdR1nDgbQT5CaIt2VB3931NdteUaA6dF39p2FAHFtzMHQeqjbWJk+HUj3Cg0l9CBH1z3o61CiI9gH4UDChbLekST0Gg9prMqLoNfIfj+taR2cbkDy0+P5Vmg0Gns/CihHF9GI0bLPIfnv7qCGAuF4WD1jlO06aUdBJ2P4/p7KmewjWxbZnVMwZgpA7zLEI2mYoSASqxMtrrRZpCMWnb/Hn8nWG4dkglJP8R1A9Q/OjGvKNBqfl6zQmGhLiOD6KwEtAWrQJJM93JYtrqS2ugipF6/WwHtPnzOtS+S9sUr7/AHs2bebU/Xqoe6kmJHmRvUtx2OmoH17qgcx0pDiyNraj8uvrqBix20HX8qkJ6/Xr/Kort2dKaQpMiEbDlXamTqffWraZtdh9a0QEB0AqXESmbdV/WoUtRmbnyk7D63qXup1B05efn+X+1auJJA35n8vOnFEzlbOS+Ub7D30BiJIk89/KixbBJPIbefIn5j31BiXgRyoeWNOkJMSW189h0qFFgfXTSi7iyZI06/P8vfW0Xn56U4qiGwVjsDvPy/X51zcGh5US9oEz00/E/wDx91QXhqI5b02IkwuPaxcW4oBKTo0xqMvI+Zo3szjltYzvbrhEYPmOsS3iAMcs0e6k15sx+t9T+VQ3TuPL9KaEexYbEWLozWrlt/6HB+R86F4ngVys05SAYYrOXTl+XOvAsRjGW+FLnu5hhyHhgmOupp9iO3RtW+6wi3AMoU3bjscxAglbbMwQeRJ31qnlC24Kvj8ez3GZioJMwwMgcp9kVld4vNiHa9cDO7mWYMiAnacoUQdNepk86ysNsTKolufCKTPPz26bCuHxCqMpknoNP0rKyrbcuTt44CuCCULOoXXQAzpA3Pvp0qk+Q+ump9tZWVUeDGX1M7ZQu5P18Ki7yTAGvuj1/pWVlSSdW7BO5JHTb/epvAgiPL9KysoQyQXPZOgHM+3l9a1OhgawfIbfrWVlUgNvjtPD7/yodMSwOmvWdaysqWNDGzjGbTKJGk8h7OdTiACTv13Mfl5VlZTQjQaNhqdvP1mpR1Jk/L1VlZQykTG8FWT7dKX4i7m1IAjbTX1k1lZQWgFrh2rVtZ1O3L8/0rKymwkFj4c67VQZ6Dfz0kD1RqfdWVlBDJTpP1rS/EX8ukmW5jpz/Ae2srKBGkvAghdPwjSocU0iBodB7T1rKyo7ldjYXWBsB9fnXGItwDpWVlWQLVPh16T79fhUVxNJ+taysoAHRYn1/DKKjS3mdVmMzBZ3jMwH41qspgL+I9mnbF3+7INu33eckw0MozGIgnwufaKCxXZNxnGcBAxCE6kgbZojUisrKy15OEVXkw1ZtLBAOAjncWeejflWVlZWO5nL7sj/2Q=="
                    alt="Paella dish"
                  />
                  <CardContent sx={{ flexGrow: 1 }}>
                    <Typography variant="body2" color="text.secondary">

                      {shop.info}
                    </Typography>

                  </CardContent>


                </Card>
              </CardActionArea>

            </Grid>
          })}





        </Grid>
      </Container>


    </HomePage >
  )
}



export const getStaticProps = async (ctx) => {
  const queryClient = new QueryClient();

  // await queryClient.prefetchQuery('getShops', async () => {
  //   const data = await shopService.getShops();
  //   return data;
  // }, { refetchOnWindowFocus: false });

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    }
  }
}

